pipeline:
  name: Go App - build and deploy
  identifier: Go_App_build_and_deploy
  projectIdentifier: devx_jc
  orgIdentifier: sandbox
  tags: {}
  stages:
    - stage:
        name: Example
        identifier: Example
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - parallel:
                  - step:
                      type: ShellScript
                      name: ShellScript
                      identifier: ShellScript
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: echo "helo world"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
                  - step:
                      type: ShellScript
                      name: ShellScript_2
                      identifier: ShellScript_2
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: echo "this is version 2"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
        tags: {}
