pipeline:
  name: Go App - build and deploy
  identifier: Go_App_build_and_deploy
  projectIdentifier: devx_jc
  orgIdentifier: sandbox
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: JC_Github_connector
        repoName: simple-pov-app
        build: <+input>
  stages:
    - stage:
        name: Build and Test
        identifier: Build_and_Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run
                  identifier: Run
                  spec:
                    shell: Sh
                    command: echo "hello world"
