pipeline:
  name: Go App - build and deploy
  identifier: Go_App_build_and_deploy
  projectIdentifier: devx_jc
  orgIdentifier: sandbox
  tags: {}
  stages:
    - stage:
        name: Example
        identifier: Example
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - parallel:
                  - step:
                      name: ShellScript
                      identifier: ShellScript
                      template:
                        templateRef: shell_script_1
                        versionLabel: 0.0.1
                  - step:
                      name: ShellScript_2
                      identifier: ShellScript_2
                      template:
                        templateRef: shell_script_2
                        versionLabel: 0.0.1
                  - step:
                      type: ShellScript
                      name: ShellScript_3
                      identifier: ShellScript_3
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: echo "this is my new branch"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
        tags: {}
